// Code generated by go-swagger; DO NOT EDIT.

package alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSendDocumentAlertParams creates a new SendDocumentAlertParams object
// with the default values initialized.
func NewSendDocumentAlertParams() *SendDocumentAlertParams {
	var ()
	return &SendDocumentAlertParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSendDocumentAlertParamsWithTimeout creates a new SendDocumentAlertParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSendDocumentAlertParamsWithTimeout(timeout time.Duration) *SendDocumentAlertParams {
	var ()
	return &SendDocumentAlertParams{

		timeout: timeout,
	}
}

// NewSendDocumentAlertParamsWithContext creates a new SendDocumentAlertParams object
// with the default values initialized, and the ability to set a context for a request
func NewSendDocumentAlertParamsWithContext(ctx context.Context) *SendDocumentAlertParams {
	var ()
	return &SendDocumentAlertParams{

		Context: ctx,
	}
}

// NewSendDocumentAlertParamsWithHTTPClient creates a new SendDocumentAlertParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSendDocumentAlertParamsWithHTTPClient(client *http.Client) *SendDocumentAlertParams {
	var ()
	return &SendDocumentAlertParams{
		HTTPClient: client,
	}
}

/*SendDocumentAlertParams contains all the parameters to send to the API endpoint
for the send document alert operation typically these are written to a http.Request
*/
type SendDocumentAlertParams struct {

	/*Chatid
	  chat id

	*/
	Chatid int64
	/*Extension
	  document extension (pdf, doc, xls)

	*/
	Extension string
	/*Message
	  raw document data encoded in base64

	*/
	Message *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the send document alert params
func (o *SendDocumentAlertParams) WithTimeout(timeout time.Duration) *SendDocumentAlertParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send document alert params
func (o *SendDocumentAlertParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send document alert params
func (o *SendDocumentAlertParams) WithContext(ctx context.Context) *SendDocumentAlertParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send document alert params
func (o *SendDocumentAlertParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the send document alert params
func (o *SendDocumentAlertParams) WithHTTPClient(client *http.Client) *SendDocumentAlertParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the send document alert params
func (o *SendDocumentAlertParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChatid adds the chatid to the send document alert params
func (o *SendDocumentAlertParams) WithChatid(chatid int64) *SendDocumentAlertParams {
	o.SetChatid(chatid)
	return o
}

// SetChatid adds the chatid to the send document alert params
func (o *SendDocumentAlertParams) SetChatid(chatid int64) {
	o.Chatid = chatid
}

// WithExtension adds the extension to the send document alert params
func (o *SendDocumentAlertParams) WithExtension(extension string) *SendDocumentAlertParams {
	o.SetExtension(extension)
	return o
}

// SetExtension adds the extension to the send document alert params
func (o *SendDocumentAlertParams) SetExtension(extension string) {
	o.Extension = extension
}

// WithMessage adds the message to the send document alert params
func (o *SendDocumentAlertParams) WithMessage(message *string) *SendDocumentAlertParams {
	o.SetMessage(message)
	return o
}

// SetMessage adds the message to the send document alert params
func (o *SendDocumentAlertParams) SetMessage(message *string) {
	o.Message = message
}

// WriteToRequest writes these params to a swagger request
func (o *SendDocumentAlertParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param chatid
	if err := r.SetPathParam("chatid", swag.FormatInt64(o.Chatid)); err != nil {
		return err
	}

	// path param extension
	if err := r.SetPathParam("extension", o.Extension); err != nil {
		return err
	}

	if o.Message != nil {
		if err := r.SetBodyParam(o.Message); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
