// Code generated by go-swagger; DO NOT EDIT.

package alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSendImageAlertParams creates a new SendImageAlertParams object
// with the default values initialized.
func NewSendImageAlertParams() *SendImageAlertParams {
	var ()
	return &SendImageAlertParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSendImageAlertParamsWithTimeout creates a new SendImageAlertParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSendImageAlertParamsWithTimeout(timeout time.Duration) *SendImageAlertParams {
	var ()
	return &SendImageAlertParams{

		timeout: timeout,
	}
}

// NewSendImageAlertParamsWithContext creates a new SendImageAlertParams object
// with the default values initialized, and the ability to set a context for a request
func NewSendImageAlertParamsWithContext(ctx context.Context) *SendImageAlertParams {
	var ()
	return &SendImageAlertParams{

		Context: ctx,
	}
}

// NewSendImageAlertParamsWithHTTPClient creates a new SendImageAlertParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSendImageAlertParamsWithHTTPClient(client *http.Client) *SendImageAlertParams {
	var ()
	return &SendImageAlertParams{
		HTTPClient: client,
	}
}

/*SendImageAlertParams contains all the parameters to send to the API endpoint
for the send image alert operation typically these are written to a http.Request
*/
type SendImageAlertParams struct {

	/*Chatid
	  chat id

	*/
	Chatid int64
	/*Message
	  message you want to send enocded in base64 format

	*/
	Message *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the send image alert params
func (o *SendImageAlertParams) WithTimeout(timeout time.Duration) *SendImageAlertParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the send image alert params
func (o *SendImageAlertParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the send image alert params
func (o *SendImageAlertParams) WithContext(ctx context.Context) *SendImageAlertParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the send image alert params
func (o *SendImageAlertParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the send image alert params
func (o *SendImageAlertParams) WithHTTPClient(client *http.Client) *SendImageAlertParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the send image alert params
func (o *SendImageAlertParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChatid adds the chatid to the send image alert params
func (o *SendImageAlertParams) WithChatid(chatid int64) *SendImageAlertParams {
	o.SetChatid(chatid)
	return o
}

// SetChatid adds the chatid to the send image alert params
func (o *SendImageAlertParams) SetChatid(chatid int64) {
	o.Chatid = chatid
}

// WithMessage adds the message to the send image alert params
func (o *SendImageAlertParams) WithMessage(message *string) *SendImageAlertParams {
	o.SetMessage(message)
	return o
}

// SetMessage adds the message to the send image alert params
func (o *SendImageAlertParams) SetMessage(message *string) {
	o.Message = message
}

// WriteToRequest writes these params to a swagger request
func (o *SendImageAlertParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param chatid
	if err := r.SetPathParam("chatid", swag.FormatInt64(o.Chatid)); err != nil {
		return err
	}

	if o.Message != nil {
		if err := r.SetBodyParam(o.Message); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
