// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/weAutomateEverything/prognosisHalBot/models"
)

// NewInvokeCalloutParams creates a new InvokeCalloutParams object
// with the default values initialized.
func NewInvokeCalloutParams() *InvokeCalloutParams {
	var ()
	return &InvokeCalloutParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInvokeCalloutParamsWithTimeout creates a new InvokeCalloutParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInvokeCalloutParamsWithTimeout(timeout time.Duration) *InvokeCalloutParams {
	var ()
	return &InvokeCalloutParams{

		timeout: timeout,
	}
}

// NewInvokeCalloutParamsWithContext creates a new InvokeCalloutParams object
// with the default values initialized, and the ability to set a context for a request
func NewInvokeCalloutParamsWithContext(ctx context.Context) *InvokeCalloutParams {
	var ()
	return &InvokeCalloutParams{

		Context: ctx,
	}
}

// NewInvokeCalloutParamsWithHTTPClient creates a new InvokeCalloutParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInvokeCalloutParamsWithHTTPClient(client *http.Client) *InvokeCalloutParams {
	var ()
	return &InvokeCalloutParams{
		HTTPClient: client,
	}
}

/*InvokeCalloutParams contains all the parameters to send to the API endpoint
for the invoke callout operation typically these are written to a http.Request
*/
type InvokeCalloutParams struct {

	/*Body
	  message you want to send enocded in base64 format

	*/
	Body *models.SendCalloutRequest
	/*Chatid
	  chat id

	*/
	Chatid int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the invoke callout params
func (o *InvokeCalloutParams) WithTimeout(timeout time.Duration) *InvokeCalloutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the invoke callout params
func (o *InvokeCalloutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the invoke callout params
func (o *InvokeCalloutParams) WithContext(ctx context.Context) *InvokeCalloutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the invoke callout params
func (o *InvokeCalloutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the invoke callout params
func (o *InvokeCalloutParams) WithHTTPClient(client *http.Client) *InvokeCalloutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the invoke callout params
func (o *InvokeCalloutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the invoke callout params
func (o *InvokeCalloutParams) WithBody(body *models.SendCalloutRequest) *InvokeCalloutParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the invoke callout params
func (o *InvokeCalloutParams) SetBody(body *models.SendCalloutRequest) {
	o.Body = body
}

// WithChatid adds the chatid to the invoke callout params
func (o *InvokeCalloutParams) WithChatid(chatid int64) *InvokeCalloutParams {
	o.SetChatid(chatid)
	return o
}

// SetChatid adds the chatid to the invoke callout params
func (o *InvokeCalloutParams) SetChatid(chatid int64) {
	o.Chatid = chatid
}

// WriteToRequest writes these params to a swagger request
func (o *InvokeCalloutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param chatid
	if err := r.SetPathParam("chatid", swag.FormatInt64(o.Chatid)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
