// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/weAutomateEverything/prognosisHalBot/models"
)

// InvokeCalloutReader is a Reader for the InvokeCallout structure.
type InvokeCalloutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InvokeCalloutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewInvokeCalloutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewInvokeCalloutDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewInvokeCalloutOK creates a InvokeCalloutOK with default headers values
func NewInvokeCalloutOK() *InvokeCalloutOK {
	return &InvokeCalloutOK{}
}

/*InvokeCalloutOK handles this case with default header values.

Message Sent successfully
*/
type InvokeCalloutOK struct {
}

func (o *InvokeCalloutOK) Error() string {
	return fmt.Sprintf("[POST /api/callout/{chatid}][%d] invokeCalloutOK ", 200)
}

func (o *InvokeCalloutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewInvokeCalloutDefault creates a InvokeCalloutDefault with default headers values
func NewInvokeCalloutDefault(code int) *InvokeCalloutDefault {
	return &InvokeCalloutDefault{
		_statusCode: code,
	}
}

/*InvokeCalloutDefault handles this case with default header values.

unexpected error
*/
type InvokeCalloutDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the invoke callout default response
func (o *InvokeCalloutDefault) Code() int {
	return o._statusCode
}

func (o *InvokeCalloutDefault) Error() string {
	return fmt.Sprintf("[POST /api/callout/{chatid}][%d] invokeCallout default  %+v", o._statusCode, o.Payload)
}

func (o *InvokeCalloutDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
